dist: bionic

services:
  - docker

env:
  - PATH=$PATH:$(pwd)/riscv/bin

script:

  # Get tools
  - docker pull ghdl/ghdl:buster-gcc-8.3.0

  # SW check
  - /bin/bash -c "chmod u+x .ci/install.sh && .ci/install.sh"
  - /bin/bash -c "riscv32-unknown-elf-gcc -v"
  - /bin/bash -c "chmod u+x .ci/sw_check.sh && .ci/sw_check.sh"

  # HW check
  - >
    docker run -t -v `pwd`:/mnt/data ghdl/ghdl:buster-gcc-8.3.0
    /bin/bash -c "chmod u+x /mnt/data/.ci/hw_check.sh && /mnt/data/.ci/hw_check.sh"

notifications:
  email:
    on_success: never
    on_failure: always
