name: 'Deploy SW Framework Documentation to GitHub-Pages'

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: '🛠️ Modifying Doxyfile'
      run: |
        ls -al ./docs
        sed -i 's/$(PWD)\/../$(GITHUB_WORKSPACE)/g' ./docs/Doxyfile
        cat ./docs/Doxyfile

    - name: '📚 Generate Doxygen Documentation'
      uses: mattnotmitt/doxygen-action@v1.2.1
      with:
        working-directory: '.'
        doxyfile-path: 'docs/Doxyfile'

    - name: '🚀 Deploy to GitHub-Pages'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
