name: 'Deploy SW Framework Documentation to GitHub-Pages'

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: '🛠️ Modifying Doxyfile'
      run: |
        /bin/bash -c "rm -rf $GITHUB_WORKSPACE/docs/doxygen_build && mkdir $GITHUB_WORKSPACE/docs/doxygen_build"
        ls -al ./docs
        /bin/bash -c "sed -i 's/$(PWD)\/../$(GITHUB_WORKSPACE)/g' $(GITHUB_WORKSPACE)/docs/Doxyfile"

    - name: '📚 Generate Doxygen Documentation'
      uses: mattnotmitt/doxygen-action@v1.2.1
      with:
        working-directory: './docs/doxygen_build/'
        doxyfile-path: '../Doxyfile'

    - name: '🚀 Deploy to GitHub-Pages'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/doxygen_build/html
