# Generate doxygen-based documentation and deploy it to neorv32 github-pages

name: 'Deploy SW Framework Documentation to GitHub-Pages'

on:
  push:
    branches:
    - master
    paths:
    - 'sw/**'
  pull_request:
    branches:
    - master
    paths:
    - 'sw/**'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    name: 'Generate and Deploy SW Framework Documentation'

    steps:

    - name: '🧰 Repository Checkout'
      uses: actions/checkout@v2

    - name: '🛠️ Modifying Doxyfile'
      run: |
        ls -al ./docs
        sed -i 's/$(PWD)\/../$(GITHUB_WORKSPACE)/g' ./docs/Doxyfile

    - name: '📚 Generate Doxygen Documentation'
      uses: mattnotmitt/doxygen-action@v1.2.1
      with:
        working-directory: '.'
        doxyfile-path: 'docs/Doxyfile'

    - name: '🚀 Deploy to GitHub-Pages'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doxygen_build/html
