# Check NEORV32 software framework and test processor using cpu_test program

name: 'SW & HW Test'

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - main
    - releases/*
  pull_request:
    branches:
    - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: '⚙️ SW & HW Test'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Set env variables
      - name: '💻 Set environement variables'
        run: |
          echo $PATH
          echo "$HOME/riscv/bin" >> $GITHUB_PATH
          echo "PATH=$PATH:$HOME/riscv/bin" >> $GITHUB_ENV
          echo $PATH

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: '💾 Checkout'
        uses: actions/checkout@v2

      # Get gcc toolchain
      - name: '🔧 Setup RISC-V GCC'
        run: |
          /bin/bash -c "chmod u+x ./.ci/install.sh && ./.ci/install.sh"

      # Run software fremwork tests
      - name: '▶️ Run SW Tests'
        run: |
          echo $PATH
          riscv32-unknown-elf-gcc -v
          /bin/bash -c "chmod u+x ./.ci/sw_check.sh && ./.ci/sw_check.sh"  

      # Run hardware tests
      - name: '▶️ Run HW Tests'
        run: /bin/bash -c "chmod u+x ./.ci/hw_check.sh && ./.ci/hw_check.sh"
